#!/usr/bin/env python3
"""Generate well-formed Mux programs to stress bindings, blocks, and captures.

The corpus in test_scripts/ is hand-written, so it only covers shapes someone
thought to write. This emits programs mechanically across the axes that have
historically produced bugs - binding forms, block forms, closure captures,
shadowing, references, list element references, strings, collections,
optionals, results, tuples, generic classes, enum payloads, loop exits, and
early returns - and is meant to be run through the gates that already exist:
compile, execute, and scripts/leak-check.sh.

Differential oracle: every program computes one value through two paths (local
vs captured vs referenced vs boxed in a generic) and prints the two results
with a unique oracle ID. The generator writes a JSON manifest beside each Mux
file with the expected oracle values and covered feature buckets. The runner
rejects missing or unequal pairs, mismatches against the manifest, and
multi-seed campaigns that miss a core feature.

Every program is deterministic given its seed, so a failing case reproduces
exactly: rerun with the same --seed. Every while loop counts a bounded
counter and every list is finite, so programs terminate by construction.

Usage:
  scripts/generate-programs.py --out DIR --count N [--start-seed S]
  scripts/generate-programs.py --out DIR --seed S
"""

import argparse
import json
import pathlib
import random
import tempfile
from dataclasses import dataclass, field

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
SYSTEM_TEMP_ROOT = pathlib.Path(tempfile.gettempdir()).resolve()
ALLOWED_OUTPUT_ROOTS = (REPO_ROOT, SYSTEM_TEMP_ROOT)

CORE_FEATURES = [
    "closure-capture",
    "collections",
    "enum-payload",
    "generic-int",
    "generic-string",
    "loop-break-continue",
    "optional-none",
    "optional-some",
    "reference-list-element",
    "result-ok-err",
    "tuple-field",
    "early-return-cleanup",
]

INT_NAMES = ["a", "b", "c", "d", "e"]
STR_NAMES = ["s", "t", "u"]

# Mutable globals shared by every generated program: read, mutated, and
# captured by closures in the global scenes below.
HEADER = """// Generated by scripts/generate-programs.py (seed {seed}).
// Do not edit by hand; regenerate instead.
const int SEED_MARK = {mark}

int G_A = 7
int G_B = 11
string G_S = "gs"

class Holder<T> {{
    T value

    common func from(T val) returns Holder<T> {{
        auto holder = Holder<T>.new()
        holder.value = val
        return holder
    }}

    func get() returns T {{
        return self.value
    }}
}}

enum Shape {{
    Point,
    Dot(int n),
    Label(string text)
}}

func add_pair(int x, int y) returns int {{
    return x + y
}}

func bump_global(int by) returns int {{
    G_A = G_A + by
    return G_A
}}

func choose_result(int x) returns result<int, string> {{
    if x > 0 {{ return ok(x) }}
    return err("neg")
}}

func early_return_probe(int x) returns int {{
    auto held = Holder<string>.from("early" + x.to_string())
    if x > 0 {{
        return held.get().length() + x
    }}
    return x
}}
"""


@dataclass(frozen=True)
class Binding:
    name: str
    mux_type: str


@dataclass
class Manifest:
    seed: int
    features: set[str] = field(default_factory=set)
    feature_oracles: dict[str, str] = field(default_factory=dict)
    expected_oracles: dict[str, str] = field(default_factory=dict)
    required_oracles: set[str] = field(default_factory=set)

    def as_json(self) -> str:
        payload = {
            "seed": self.seed,
            "features": sorted(self.features),
            "feature_oracles": dict(sorted(self.feature_oracles.items())),
            "expected_oracles": dict(sorted(self.expected_oracles.items())),
            "required_oracles": sorted(self.required_oracles),
        }
        return json.dumps(payload, indent=2, sort_keys=True) + "\n"


@dataclass(frozen=True)
class GeneratedProgram:
    source: str
    manifest: Manifest


def confined_path(candidate: pathlib.Path, what: str) -> pathlib.Path:
    resolved = candidate.resolve()
    if any(
        resolved == root or root in resolved.parents for root in ALLOWED_OUTPUT_ROOTS
    ):
        return resolved
    roots = ", ".join(str(root) for root in ALLOWED_OUTPUT_ROOTS)
    raise ValueError(f"{what} {resolved} is outside allowed roots: {roots}")


class Gen:
    def __init__(self, rng: random.Random) -> None:
        self.rng = rng
        self.next_id = 0
        self.manifest = Manifest(seed=0)

    def fresh(self, base: str) -> str:
        self.next_id += 1
        return f"{base}{self.next_id}"

    def note_feature(self, feature: str) -> None:
        self.manifest.features.add(feature)

    # ----- expressions -----------------------------------------------------

    def int_expr(self, scope: list[Binding], depth: int = 0) -> str:
        """An int expression over in-scope ints and constants."""
        pool = ["SEED_MARK", "G_A"] + [
            binding.name for binding in scope if binding.mux_type == "int"
        ]
        choice = self.rng.random()
        if depth < 2 and choice < 0.40:
            op = self.rng.choice(["+", "-", "*"])
            return (
                f"({self.int_expr(scope, depth + 1)} {op} "
                f"{self.int_expr(scope, depth + 1)})"
            )
        if choice < 0.72 and pool:
            return self.rng.choice(pool)
        return str(self.rng.randint(0, 20))

    def string_expr(self, ints: list[str]) -> str:
        """A string expression over globals and in-scope values."""
        kind = self.rng.random()
        if kind < 0.35:
            base = self.rng.choice(["alpha", "b,c,d", "hello world"])
            if self.rng.random() < 0.5:
                sep = self.rng.choice([",", " "])
                return f'"{base}".split("{sep}")[0]'
            return f'"{base}"'
        if kind < 0.65 and ints:
            return f'"{self.fresh("k")}=" + {self.rng.choice(ints)}.to_string()'
        if kind < 0.85:
            return f'G_S + "{self.rng.randint(0, 9)}"'
        return f'"s{self.rng.randint(0, 99)}"'

    # ----- statements ------------------------------------------------------

    def emit_print_int(self, pad: str, label: str, expr: str, out: list[str]) -> None:
        out.append(f'{pad}print("{label}: " + ({expr}).to_string())')

    def emit_expected_int_oracle(
        self, pad: str, feature: str, expr: str, expected: int, out: list[str]
    ) -> None:
        oracle_id = self.fresh("oracle")
        actual = self.fresh("actual")
        out.append(f"{pad}auto {actual} = {expr}")
        self.emit_print_int(pad, f"@@oracle:{oracle_id}:p1", actual, out)
        self.emit_print_int(pad, f"@@oracle:{oracle_id}:p2", actual, out)
        self.manifest.expected_oracles[oracle_id] = str(expected)
        self.manifest.required_oracles.add(oracle_id)
        self.manifest.feature_oracles[feature] = oracle_id

    def stmt(
        self,
        scope: list[Binding],
        ints: list[str],
        indent: str,
        depth: int,
        out: list[str],
    ) -> None:
        """One statement or block, possibly nesting."""
        pad = indent
        kind = self.rng.random()

        if kind < 0.16 or depth >= 3:
            self.plain_decl(pad, scope, ints, out)
            return

        if kind < 0.27:
            self.if_else_scene(pad, scope, ints, depth, out)
            return

        if kind < 0.36:
            self.while_scene(pad, scope, ints, depth, out)
            return

        if kind < 0.45:
            self.for_scene(pad, scope, ints, depth, out)
            return

        if kind < 0.53:
            self.match_scene(pad, scope, ints, depth, out)
            return

        if kind < 0.63:
            self.closure_scene(pad, scope, out)
            return

        if kind < 0.71:
            self.reference_scene(pad, scope, ints, out)
            return

        if kind < 0.79:
            self.global_scene(pad, scope, ints, out)
            return

        if kind < 0.87:
            self.generic_scene(pad, scope, ints, out)
            return

        if kind < 0.94:
            self.enum_scene(pad, scope, ints, depth, out)
            return

        self.differential_scene(pad, out)

    # ----- individual scenes ----------------------------------------------

    def plain_decl(
        self, pad: str, scope: list[Binding], ints: list[str], out: list[str]
    ) -> None:
        name = self.fresh(self.rng.choice(INT_NAMES))
        out.append(f"{pad}auto {name} = {self.int_expr(scope)}")
        ints.append(name)
        scope.append(Binding(name, "int"))
        self.emit_print_int(pad, name, name, out)
        if self.rng.random() < 0.35:
            sname = self.fresh(self.rng.choice(STR_NAMES))
            out.append(f'{pad}auto {sname} = "{name}=" + {name}.to_string()')
            out.append(f"{pad}print({sname})")

    def if_else_scene(
        self,
        pad: str,
        scope: list[Binding],
        ints: list[str],
        depth: int,
        out: list[str],
    ) -> None:
        shadow_target = self.rng.choice(scope).name if scope else None
        out.append(f"{pad}if {self.int_expr(scope)} < {self.int_expr(scope)} {{")
        inner_s, inner_i = scope[:], ints[:]
        name = shadow_target or self.fresh(self.rng.choice(INT_NAMES))
        out.append(f"{pad}    auto {name} = {self.int_expr(inner_s)}")
        inner_s.append(Binding(name, "int"))
        inner_i.append(name)
        self.block_body(inner_s, inner_i, pad + "    ", depth + 1, out)
        out.append(f'{pad}    print("shadow-if {name}: " + {name}.to_string())')
        out.append(f"{pad}}} else {{")
        self.block_body(scope[:], ints[:], pad + "    ", depth + 1, out)
        out.append(f"{pad}}}")

    def while_scene(
        self,
        pad: str,
        scope: list[Binding],
        ints: list[str],
        depth: int,
        out: list[str],
    ) -> None:
        i = self.fresh("i")
        limit = self.rng.randint(1, 3)
        out.append(f"{pad}int {i} = 0")
        out.append(f"{pad}while {i} < {limit} {{")
        inner_s, inner_i = scope + [Binding(i, "int")], ints + [i]
        self.block_body(inner_s, inner_i, pad + "    ", depth + 1, out)
        out.append(f"{pad}    {i} = {i} + 1")
        out.append(f"{pad}}}")

    def for_scene(
        self,
        pad: str,
        scope: list[Binding],
        ints: list[str],
        depth: int,
        out: list[str],
    ) -> None:
        lst = self.fresh("xs")
        elems = ", ".join(str(self.rng.randint(0, 9)) for _ in range(3))
        out.append(f"{pad}list<int> {lst} = [{elems}]")
        lv = self.fresh("x")
        out.append(f"{pad}for int {lv} in {lst} {{")
        inner_s, inner_i = scope + [Binding(lv, "int")], ints + [lv]
        self.block_body(inner_s, inner_i, pad + "    ", depth + 1, out)
        if self.rng.random() < 0.4:
            # Reference to a list element inside the loop.
            ref = self.fresh("ref")
            out.append(f"{pad}    auto {ref} = &{lst}[0]")
            out.append(f'{pad}    print("&{lst}[0]: " + (*{ref}).to_string())')
        out.append(f'{pad}    print("loop {lv}: " + {lv}.to_string())')
        out.append(f"{pad}}}")

    def match_scene(
        self,
        pad: str,
        scope: list[Binding],
        ints: list[str],
        depth: int,
        out: list[str],
    ) -> None:
        opt_src = self.fresh("m")
        if self.rng.random() < 0.5:
            initializer = f"some({self.int_expr(scope)})"
            self.note_feature("optional-some")
        else:
            initializer = "none"
            self.note_feature("optional-none")
        out.append(f"{pad}optional<int> {opt_src} = {initializer}")
        bound = self.fresh("v")
        out.append(f"{pad}match {opt_src} {{")
        out.append(f"{pad}    some({bound}) {{")
        inner_s, inner_i = scope + [Binding(bound, "int")], ints + [bound]
        self.block_body(inner_s, inner_i, pad + "        ", depth + 1, out)
        self.emit_print_int(pad + "        ", f"match {bound}", bound, out)
        out.append(f"{pad}    }}")
        out.append(f'{pad}    none {{ print("match none") }}')
        out.append(f"{pad}}}")

    def closure_scene(self, pad: str, scope: list[Binding], out: list[str]) -> None:
        self.note_feature("closure-capture")
        cap = self.fresh("cap")
        out.append(f"{pad}auto {cap} = {self.int_expr(scope)}")
        inner_s = scope + [Binding(cap, "int")]
        fname = self.fresh("f")
        out.append(f"{pad}auto {fname} = func() returns int {{")
        if self.rng.random() < 0.5:
            out.append(f"{pad}    {cap}++")
            out.append(f"{pad}    return {cap}")
        else:
            out.append(f"{pad}    return add_pair({cap}, {self.int_expr(inner_s)})")
        out.append(f"{pad}}}")
        self.emit_print_int(pad, f"closure {fname}", f"{fname}()", out)
        if self.rng.random() < 0.6:
            gname = self.fresh("g")
            out.append(f"{pad}auto {gname} = func() returns int {{")
            out.append(f"{pad}    return {cap} * 2")
            out.append(f"{pad}}}")
            self.emit_print_int(pad, f"closure {gname}", f"{gname}()", out)

    def reference_scene(
        self, pad: str, scope: list[Binding], ints: list[str], out: list[str]
    ) -> None:
        target = self.rng.choice(ints) if ints else None
        if target is None:
            target = self.fresh("r0")
            out.append(f"{pad}auto {target} = {self.rng.randint(1, 9)}")
            ints.append(target)
            scope.append(Binding(target, "int"))
        ref = self.fresh("ref")
        out.append(f"{pad}auto {ref} = &{target}")
        self.emit_print_int(pad, f"deref {ref}", f"*{ref}", out)
        if self.rng.random() < 0.6:
            out.append(f"{pad}*{ref} = *{ref} + {self.rng.randint(1, 5)}")
            self.emit_print_int(pad, target, target, out)
        if self.rng.random() < 0.5:
            self.note_feature("reference-list-element")
            lst = self.fresh("ys")
            elems = ", ".join(str(self.rng.randint(1, 9)) for _ in range(3))
            out.append(f"{pad}list<int> {lst} = [{elems}]")
            lref = self.fresh("eref")
            out.append(f"{pad}auto {lref} = &{lst}[{self.rng.randint(0, 2)}]")
            self.emit_print_int(pad, f"elem {lref}", f"*{lref}", out)

    def global_scene(
        self, pad: str, scope: list[Binding], ints: list[str], out: list[str]
    ) -> None:
        scene = self.rng.random()
        if scene < 0.4:
            # Closure mutating a global.
            gname = self.fresh("gf")
            out.append(f"{pad}auto {gname} = func() returns int {{")
            out.append(f"{pad}    G_B = G_B + 1")
            out.append(f"{pad}    return G_B")
            out.append(f"{pad}}}")
            self.emit_print_int(pad, f"global-closure {gname}", f"{gname}()", out)
        elif scene < 0.7:
            # Call the helper that mutates G_A; capture it too.
            self.emit_print_int(
                pad, "bump_global", f"bump_global({self.int_expr(scope)})", out
            )
            cap = self.fresh("gcap")
            out.append(f"{pad}auto {cap} = func() returns int {{")
            out.append(f"{pad}    return G_A * 3")
            out.append(f"{pad}}}")
            self.emit_print_int(pad, f"gcap {cap}", f"{cap}()", out)
        else:
            # Global read into a local, then shadowed locally.
            lname = self.fresh("gl")
            out.append(f"{pad}auto {lname} = G_B + {self.int_expr(scope)}")
            ints.append(lname)
            scope.append(Binding(lname, "int"))
            self.emit_print_int(pad, lname, lname, out)

    def generic_scene(
        self, pad: str, scope: list[Binding], ints: list[str], out: list[str]
    ) -> None:
        box = self.fresh("h")
        if self.rng.random() < 0.5:
            self.note_feature("generic-int")
            out.append(f"{pad}auto {box} = Holder<int>.from({self.int_expr(scope)})")
            self.emit_print_int(pad, f"holder {box}", f"{box}.get()", out)
            cap = self.fresh("hcap")
            out.append(f"{pad}auto {cap} = func() returns int {{")
            out.append(f"{pad}    return {box}.get() + 1")
            out.append(f"{pad}}}")
            self.emit_print_int(pad, f"holder-cap {cap}", f"{cap}()", out)
        else:
            self.note_feature("generic-string")
            sval = self.string_expr(ints)
            out.append(f"{pad}auto {box} = Holder<string>.from({sval})")
            out.append(f'{pad}print("holder-s {box}: " + {box}.get())')

    def enum_scene(
        self,
        pad: str,
        scope: list[Binding],
        ints: list[str],
        depth: int,
        out: list[str],
    ) -> None:
        self.note_feature("enum-payload")
        variant = self.rng.random()
        shape = self.fresh("sh")
        if variant < 0.34:
            out.append(f"{pad}auto {shape} = Shape.Point")
            out.append(f"{pad}match {shape} {{")
            out.append(f'{pad}    Point {{ print("shape point") }}')
            out.append(f'{pad}    _ {{ print("shape other") }}')
            out.append(f"{pad}}}")
        elif variant < 0.67:
            payload = self.int_expr(scope)
            out.append(f"{pad}auto {shape} = Shape.Dot({payload})")
            b = self.fresh("d")
            out.append(f"{pad}match {shape} {{")
            out.append(f"{pad}    Dot({b}) {{")
            inner_s, inner_i = scope + [Binding(b, "int")], ints + [b]
            self.block_body(inner_s, inner_i, pad + "        ", depth + 1, out)
            self.emit_print_int(pad + "        ", "dot", b, out)
            out.append(f"{pad}    }}")
            out.append(f'{pad}    _ {{ print("shape not dot") }}')
            out.append(f"{pad}}}")
        else:
            sval = self.string_expr(ints)
            out.append(f"{pad}auto {shape} = Shape.Label({sval})")
            b = self.fresh("lbl")
            out.append(f"{pad}match {shape} {{")
            out.append(f'{pad}    Label({b}) {{ print("label: " + {b}) }}')
            out.append(f'{pad}    _ {{ print("shape not label") }}')
            out.append(f"{pad}}}")

    def differential_scene(
        self,
        pad: str,
        out: list[str],
        *,
        required: bool = False,
    ) -> None:
        """One computation through two bindings; runner requires p1 == p2."""
        oracle_id = self.fresh("oracle")
        value = self.rng.randint(1, 9)
        delta = self.rng.randint(1, 5)
        expected = value + delta * self.seed_mark()
        path = self.rng.random()

        v1 = self.fresh("p1v")
        out.append(f"{pad}auto {v1} = {value}")
        out.append(f"{pad}{v1} = {v1} + {delta} * SEED_MARK")

        if path < 0.34:
            # Same computation through a closure capture.
            v2 = self.fresh("p2v")
            out.append(f"{pad}auto {v2} = {value}")
            fn = self.fresh("df")
            out.append(f"{pad}auto {fn} = func() returns int {{")
            out.append(f"{pad}    {v2} = {v2} + {delta} * SEED_MARK")
            out.append(f"{pad}    return {v2}")
            out.append(f"{pad}}}")
            p2r = self.fresh("p2r")
            out.append(f"{pad}auto {p2r} = {fn}()")
        elif path < 0.67:
            # Same computation through a reference.
            v2 = self.fresh("p2v")
            out.append(f"{pad}auto {v2} = {value}")
            ref = self.fresh("dref")
            out.append(f"{pad}auto {ref} = &{v2}")
            out.append(f"{pad}*{ref} = *{ref} + {delta} * SEED_MARK")
            p2r = self.fresh("p2r")
            out.append(f"{pad}auto {p2r} = *{ref}")
        else:
            # Same computation boxed in a generic, mutated via get/set round trip.
            box = self.fresh("dbox")
            out.append(f"{pad}auto {box} = Holder<int>.from({value})")
            fn = self.fresh("dfn")
            out.append(f"{pad}auto {fn} = func() returns int {{")
            out.append(f"{pad}    return {box}.get() + {delta} * SEED_MARK")
            out.append(f"{pad}}}")
            p2r = self.fresh("p2r")
            out.append(f"{pad}auto {p2r} = {fn}()")

        self.emit_print_int(pad, f"@@oracle:{oracle_id}:p1", v1, out)
        self.emit_print_int(pad, f"@@oracle:{oracle_id}:p2", p2r, out)
        self.manifest.expected_oracles[oracle_id] = str(expected)
        if required:
            self.manifest.required_oracles.add(oracle_id)

    def seed_mark(self) -> int:
        return (self.manifest.seed % 13) + 1

    def coverage_scene(
        self, pad: str, scope: list[Binding], ints: list[str], out: list[str]
    ) -> None:
        feature = CORE_FEATURES[(self.manifest.seed - 1) % len(CORE_FEATURES)]
        self.note_feature(feature)
        dispatch = {
            "closure-capture": lambda: self.cover_closure_capture(
                pad, scope, ints, out
            ),
            "collections": lambda: self.cover_collections(pad, out),
            "enum-payload": lambda: self.cover_enum_payload(pad, out),
            "generic-int": lambda: self.cover_generic_int(pad, out),
            "generic-string": lambda: self.cover_generic_string(pad, out),
            "loop-break-continue": lambda: self.cover_loop_break_continue(
                pad, scope, ints, out
            ),
            "optional-none": lambda: self.cover_optional_none(pad, out),
            "optional-some": lambda: self.cover_optional_some(pad, out),
            "reference-list-element": lambda: self.cover_reference_list_element(
                pad, out
            ),
            "result-ok-err": lambda: self.cover_result_ok_err(pad, out),
            "tuple-field": lambda: self.cover_tuple_field(pad, out),
            "early-return-cleanup": lambda: self.cover_early_return_cleanup(pad, out),
        }
        dispatch[feature]()

    def cover_closure_capture(
        self, pad: str, scope: list[Binding], ints: list[str], out: list[str]
    ) -> None:
        expected = 10 + self.seed_mark()
        cap = self.fresh("mustcap")
        out.append(f"{pad}auto {cap} = 10")
        fn = self.fresh("mustf")
        out.append(f"{pad}auto {fn} = func() returns int {{")
        out.append(f"{pad}    {cap} = {cap} + SEED_MARK")
        out.append(f"{pad}    return {cap}")
        out.append(f"{pad}}}")
        self.emit_print_int(pad, f"forced closure {fn}", f"{fn}()", out)
        self.emit_expected_int_oracle(pad, "closure-capture", cap, expected, out)
        scope.append(Binding(cap, "int"))
        ints.append(cap)

    def cover_collections(self, pad: str, out: list[str]) -> None:
        base = self.rng.randint(1, 6)
        xs = self.fresh("mustxs")
        out.append(f"{pad}list<int> {xs} = [{base}, {base + 1}, {base + 2}]")
        out.append(f"{pad}{xs}[1] = {xs}[1] + SEED_MARK")
        scores = self.fresh("mustmap")
        out.append(f'{pad}auto {scores} = {{"a": {base}, "b": {base + 1}}}')
        out.append(f'{pad}{scores}["c"] = {xs}[1]')
        tags = self.fresh("mustset")
        out.append(f'{pad}auto {tags} = {{"seen", "held"}}')
        out.append(f'{pad}{tags}.add("seed" + SEED_MARK.to_string())')
        self.emit_print_int(pad, f"forced collections {xs}", f"{xs}[1]", out)
        self.emit_expected_int_oracle(
            pad, "collections", f"{xs}[1]", base + 1 + self.seed_mark(), out
        )

    def cover_enum_payload(self, pad: str, out: list[str]) -> None:
        shape = self.fresh("mustshape")
        length = self.fresh("mustlen")
        out.append(f'{pad}auto {shape} = Shape.Label("seed" + SEED_MARK.to_string())')
        out.append(f"{pad}int {length} = 0")
        label = self.fresh("mustlabel")
        out.append(f"{pad}match {shape} {{")
        out.append(f"{pad}    Label({label}) {{")
        out.append(f'{pad}        print("forced label: " + {label})')
        out.append(f"{pad}        {length} = {label}.length()")
        out.append(f"{pad}    }}")
        out.append(f'{pad}    _ {{ print("forced label missing") }}')
        out.append(f"{pad}}}")
        self.emit_expected_int_oracle(
            pad,
            "enum-payload",
            length,
            len("seed") + len(str(self.seed_mark())),
            out,
        )

    def cover_generic_int(self, pad: str, out: list[str]) -> None:
        box = self.fresh("mustbox")
        expected = 20 + self.seed_mark()
        out.append(f"{pad}auto {box} = Holder<int>.from(20 + SEED_MARK)")
        self.emit_print_int(pad, f"forced generic int {box}", f"{box}.get()", out)
        self.emit_expected_int_oracle(pad, "generic-int", f"{box}.get()", expected, out)

    def cover_generic_string(self, pad: str, out: list[str]) -> None:
        box = self.fresh("mustboxs")
        out.append(
            f'{pad}auto {box} = Holder<string>.from("seed" + SEED_MARK.to_string())'
        )
        out.append(f'{pad}print("forced generic string: " + {box}.get())')
        self.emit_expected_int_oracle(
            pad,
            "generic-string",
            f"{box}.get().length()",
            len("seed") + len(str(self.seed_mark())),
            out,
        )

    def cover_loop_break_continue(
        self, pad: str, scope: list[Binding], ints: list[str], out: list[str]
    ) -> None:
        i = self.fresh("musti")
        acc = self.fresh("mustacc")
        out.append(f"{pad}int {i} = 0")
        out.append(f"{pad}int {acc} = 0")
        out.append(f"{pad}while {i} < 5 {{")
        out.append(f"{pad}    {i} = {i} + 1")
        out.append(f"{pad}    if {i} == 2 {{ continue }}")
        out.append(f"{pad}    {acc} = {acc} + {i}")
        out.append(f"{pad}    if {i} == 4 {{ break }}")
        out.append(f"{pad}}}")
        self.emit_print_int(pad, f"forced loop {acc}", acc, out)
        self.emit_expected_int_oracle(pad, "loop-break-continue", acc, 8, out)
        scope.extend([Binding(i, "int"), Binding(acc, "int")])
        ints.extend([i, acc])

    def cover_optional_none(self, pad: str, out: list[str]) -> None:
        opt = self.fresh("mustnone")
        got = self.fresh("mustgot")
        out.append(f"{pad}optional<int> {opt} = none")
        out.append(f"{pad}int {got} = -1")
        out.append(f"{pad}match {opt} {{")
        out.append(f'{pad}    some(v) {{ print("forced unexpected some") }}')
        out.append(f"{pad}    none {{")
        out.append(f'{pad}        print("forced none")')
        out.append(f"{pad}        {got} = 0")
        out.append(f"{pad}    }}")
        out.append(f"{pad}}}")
        self.emit_expected_int_oracle(pad, "optional-none", got, 0, out)

    def cover_optional_some(self, pad: str, out: list[str]) -> None:
        opt = self.fresh("mustsome")
        val = self.fresh("mustv")
        expected = 30 + self.seed_mark()
        got = self.fresh("mustgot")
        out.append(f"{pad}optional<int> {opt} = some(30 + SEED_MARK)")
        out.append(f"{pad}int {got} = 0")
        out.append(f"{pad}match {opt} {{")
        out.append(f"{pad}    some({val}) {{")
        self.emit_print_int(pad + "        ", f"forced some {val}", val, out)
        out.append(f"{pad}        {got} = {val}")
        out.append(f"{pad}    }}")
        out.append(f'{pad}    none {{ print("forced unexpected none") }}')
        out.append(f"{pad}}}")
        self.emit_expected_int_oracle(pad, "optional-some", got, expected, out)

    def cover_reference_list_element(self, pad: str, out: list[str]) -> None:
        xs = self.fresh("mustrefs")
        ref = self.fresh("mustref")
        out.append(f"{pad}list<int> {xs} = [3, 4, 5]")
        out.append(f"{pad}auto {ref} = &{xs}[1]")
        out.append(f"{pad}*{ref} = *{ref} + SEED_MARK")
        self.emit_print_int(pad, f"forced ref {ref}", f"*{ref}", out)
        self.emit_expected_int_oracle(
            pad, "reference-list-element", f"*{ref}", 4 + self.seed_mark(), out
        )

    def cover_result_ok_err(self, pad: str, out: list[str]) -> None:
        ok_result = self.fresh("mustok")
        err_result = self.fresh("musterr")
        score = self.fresh("mustscore")
        out.append(f"{pad}result<int, string> {ok_result} = choose_result(SEED_MARK)")
        out.append(f"{pad}result<int, string> {err_result} = choose_result(-1)")
        out.append(f"{pad}int {score} = 0")
        out.append(f"{pad}match {ok_result} {{")
        out.append(f"{pad}    ok(v) {{")
        out.append(f'{pad}        print("forced ok: " + v.to_string())')
        out.append(f"{pad}        {score} = {score} + v")
        out.append(f"{pad}    }}")
        out.append(f'{pad}    err(e) {{ print("forced unexpected err: " + e) }}')
        out.append(f"{pad}}}")
        out.append(f"{pad}match {err_result} {{")
        out.append(f'{pad}    ok(v) {{ print("forced unexpected ok") }}')
        out.append(f"{pad}    err(e) {{")
        out.append(f'{pad}        print("forced err: " + e)')
        out.append(f"{pad}        {score} = {score} + e.length()")
        out.append(f"{pad}    }}")
        out.append(f"{pad}}}")
        self.emit_expected_int_oracle(
            pad, "result-ok-err", score, self.seed_mark() + len("neg"), out
        )

    def cover_tuple_field(self, pad: str, out: list[str]) -> None:
        tup = self.fresh("musttuple")
        expected = 40 + self.seed_mark()
        out.append(f'{pad}auto {tup} = (40 + SEED_MARK, "tuple")')
        self.emit_print_int(pad, f"forced tuple {tup}", f"{tup}.left", out)
        out.append(f'{pad}print("forced tuple right: " + {tup}.right)')
        self.emit_expected_int_oracle(pad, "tuple-field", f"{tup}.left", expected, out)

    def cover_early_return_cleanup(self, pad: str, out: list[str]) -> None:
        value = self.fresh("mustret")
        out.append(f"{pad}auto {value} = early_return_probe(SEED_MARK)")
        self.emit_print_int(pad, f"forced early return {value}", value, out)
        self.emit_expected_int_oracle(
            pad,
            "early-return-cleanup",
            value,
            len("early") + len(str(self.seed_mark())) + self.seed_mark(),
            out,
        )

    def block_body(
        self,
        scope: list[Binding],
        ints: list[str],
        pad: str,
        depth: int,
        out: list[str],
    ) -> None:
        for _ in range(self.rng.randint(1, 3)):
            self.stmt(scope, ints, pad, depth, out)

    # ----- program ---------------------------------------------------------

    def program(self, seed: int) -> str:
        return self.generate(seed).source

    def generate(self, seed: int) -> GeneratedProgram:
        self.manifest = Manifest(seed=seed)
        self.next_id = 0
        out = [HEADER.format(seed=seed, mark=(seed % 13) + 1)]
        out.append("func main() returns void {")
        scope: list[Binding] = []
        ints: list[str] = []
        for i in range(2):
            name = self.fresh(INT_NAMES[i % len(INT_NAMES)])
            out.append(f"    auto {name} = {self.rng.randint(0, 15)}")
            scope.append(Binding(name, "int"))
            ints.append(name)
        for _ in range(self.rng.randint(5, 10)):
            self.stmt(scope, ints, "    ", 0, out)
        self.coverage_scene("    ", scope, ints, out)
        # Keep the wrong-answer oracle present even when random scene selection
        # did not choose one. More oracles may appear in nested scenes.
        self.differential_scene("    ", out, required=True)
        out.append('    print("done")')
        out.append("    return")
        out.append("}")
        return GeneratedProgram("\n".join(out) + "\n", self.manifest)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out", required=True, help="directory for generated .mux files"
    )
    parser.add_argument("--count", type=int, default=100)
    parser.add_argument("--start-seed", type=int, default=1)
    parser.add_argument(
        "--seed", type=int, help="generate exactly one seed; overrides the seed range"
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="replace generated case files that already exist",
    )
    args = parser.parse_args()

    if args.count < 1:
        parser.error("--count must be at least 1")

    try:
        out_dir = confined_path(pathlib.Path(args.out), "output directory")
    except ValueError as error:
        parser.error(str(error))
    out_dir.mkdir(parents=True, exist_ok=True)
    seeds = (
        [args.seed]
        if args.seed is not None
        else list(range(args.start_seed, args.start_seed + args.count))
    )
    paths = [out_dir / f"case_{seed:05d}.mux" for seed in seeds]
    manifest_paths = [path.with_suffix(".json") for path in paths]
    collisions = [path for path in [*paths, *manifest_paths] if path.exists()]
    if collisions and not args.overwrite:
        parser.error(
            f"{collisions[0]} already exists; pass --overwrite to replace generated cases"
        )

    for seed, path in zip(seeds, paths, strict=True):
        rng = random.Random(seed)
        generated = Gen(rng).generate(seed)
        path.write_text(generated.source, encoding="utf-8")
        path.with_suffix(".json").write_text(
            generated.manifest.as_json(), encoding="utf-8"
        )
    print(f"wrote {len(paths)} programs to {out_dir}")


if __name__ == "__main__":
    main()
